---
test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  clients:
    type: local
    number: 5
  rounds:
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 1500
    - 1500
    - 1500
    - 1500
    - 1500
    - 1500
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    - type: fixed-rate
      opts:
        tps: 100
    - type: fixed-rate
      opts:
        tps: 150
    - type: fixed-rate
      opts:
        tps: 200
    - type: fixed-rate
      opts:
        tps: 250
    - type: fixed-rate
      opts:
        tps: 300
    arguments:
      money: 15000
    callback: report/local-money/open.js
  - label: query
    description: Test description for the query performance of the deployed chaincode
    txNumber:
    - 1500
    - 1500
    - 1500
    - 1500
    - 1500
    - 1500
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    - type: fixed-rate
      opts:
        tps: 100
    - type: fixed-rate
      opts:
        tps: 150
    - type: fixed-rate
      opts:
        tps: 200
    - type: fixed-rate
      opts:
        tps: 250
    - type: fixed-rate
      opts:
        tps: 300
    callback: report/local-money/query.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
